### ISSUE TITLE
配置以太网，报告缺少bridge_eth.c

### ISSUE THREAD

**Issue by Leadrive** [espressif/esp-iot-bridge#23]
想测试以太网连接，用的ESP32S+LAN8720，在IDF的example/ethernet/basic，是测试能连上网。

编译后报缺少文件
Cannot find source file:

    /home/lubuntu/mesh/esp-iot-bridge/components/iot_bridge/priv_src/bridge_eth.c

给sales@发邮件，没见回复。

**Comment by Eavo** [comment]
方便提供下您的邮箱吗？@Leadrive

**Comment by xcguang** [comment]
请按照 readme 里面的说明，联系 sales@espressif.com

**Comment by Leadrive** [comment]
@Eavo 156744737@qq.com 谢谢
