### ISSUE TITLE
About requesting source code of USB-WiFi bridge

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-iot-bridge#29]
Hello,
I sent an email to the sales last week to request the source code of USB-SoftAP bridge. I got no response from Espressif. My email is wuyuanyi135()gmail.com . What is the normal processing time for requesting source code?

**Comment by wuyuanyi135** [comment]
Nevermind. I have implemented the missing parts myself.

**Comment by redfast00** [comment]
@wuyuanyi135 Would you be willing to share or opensource your solution?

**Comment by xcguang** [comment]
Hello, we will open these code soon, thanks
