### ISSUE TITLE
esp_modem_recov_helper.h: No such file or directory (AEGHB-45)

### ISSUE THREAD

**Issue by timschr** [espressif/esp-iot-bridge#33]
The wifi_router example is building fine when using the default configuration. but when I change from "Use Wi-Fi station interface to connect to the external network" to "Use 4G modem interface to connect to the external network" in (Top) → Component config → Bridge Configuration → The interface used to connect to the external network, I get this error: 

```
esp-iot-bridge/components/iot_bridge/src/bridge_modem.c:28:10: fatal error: esp_modem_recov_helper.h: No such file or directory
   28 | #include "esp_modem_recov_helper.h"

```

I am using esp32 and ESP-IDE v5.0, but the error also occurs with ESP-IDE v4.4

**Comment by xcguang** [comment]
Could you test on latest master?
