### ISSUE TITLE
error: esp-netif_lwip-ppp: pppos_input_tcpip failed with -1 (AEGHB-396)

### ISSUE THREAD

**Issue by AD-Codex** [espressif/esp-iot-bridge#59]
Using esp32-4g-hotspot with esp32-s3 and EC25-E chip gave error "esp-netif_lwip-ppp: pppos_input_tcpip failed with -1" . But the hotspot work with speed limit 8kps. Any reasons for this error and speed limit

**Comment by tswen** [comment]
please refer this issue https://github.com/espressif/esp-iot-solution/issues/118
