### ISSUE TITLE
Special character & (AEGHB-563)

### ISSUE THREAD

**Issue by miccgn** [espressif/esp-iot-bridge#68]
Hi,

from my experience, the code is not able to deal with the &-sign, if this is included in either the SSID or the STA password.

In both cases, the content gets truncated before the &-sign when stored to NVS.

**Comment by tswen** [comment]
Hello, thank you for your feedback. We will test and verify this part.

**Comment by tswen** [comment]
![image](https://github.com/espressif/esp-iot-bridge/assets/55544524/0a4c8545-a697-4aa3-94cb-41fd98d2b5db)
Hello, I have conducted a test, and NVS does not truncate the "&" symbol.

**Comment by miccgn** [comment]
Hi @tswen,

thanks for your analysis. However, when I tried the example "wifi_router", I had troubles connecting to an SSID with & characters. 

I can't reproduce it at the moment, as my only ESP32 is in use now, so let's close this here. For some reason (output messages on the webpage?) I assumed there was an error in the parsing routines.
