### ISSUE TITLE
Wireless NIC device (AEGHB-815)

### ISSUE THREAD

**Issue by maaamcube** [espressif/esp-iot-bridge#85]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

Hello everyone,
Does the wireless NIC works with usb devices ? i have an usb device on my stm32.
Thanks.

### Use cases

wireless NIC for usb devices

**Comment by tswen** [comment]
You can select CONFIG_BRIDGE_DATA_FORWARDING_NETIF_USB to enable the USB Device function, which is possible if your stm32's USB Host supports USB Net Class.

**Comment by maaamcube** [comment]
@tswen my stm32 can't work as host usb

**Comment by tswen** [comment]
Then it is impossible to connect to stm32, because the USB interface of esp32-S implements Net Class and can only be used as a USB Device.

**Comment by maaamcube** [comment]
@tswen usb host should be added.

**Comment by tswen** [comment]
What is the purpose of connecting stm32 via USB? Is it used for CDC communication or something else? We support USB host. For specific examples of using USB host, please refer to:

- https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host
- https://github.com/espressif/esp-iot-solution/tree/master/examples/usb/host

**Comment by maaamcube** [comment]
@tswen Yes, i'm using USB Vendor Specific communication
